### ISSUE TITLE
webpack --watch fails with error.

### ISSUE THREAD

**Issue by rmargam** [GProst/webpack-clean-obsolete-chunks#25]
/Users/a119/.nvm/versions/node/v4.8.3/bin/node /Users/a119/.nvm/versions/node/v4.8.3/lib/node_modules/npm/bin/npm-cli.js run watch --scripts-prepend-node-path=auto

> jsx-transpilier@1.0.0 watch /Users/a119/code/product
> webpack --watch

/Users/a119/code/product/node_modules/webpack-clean-obsolete-chunks/index.js:13
CleanObsoleteChunks.prototype._setOptions = function(options = {}) {
                                                             ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/a119/code/product/webpack.config.js:4:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (/Users/a119/code/product/node_modules/webpack/bin/convert-argv.js:97:18)
    at /Users/a119/code/product/node_modules/webpack/bin/convert-argv.js:104:17

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/a119/.nvm/versions/node/v4.8.3/bin/node" "/Users/a119/.nvm/versions/node/v4.8.3/lib/node_modules/npm/bin/npm-cli.js" "run" "watch" "--scripts-prepend-node-path=auto"
npm ERR! node v4.8.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! jsx-transpilier@1.0.0 watch: `webpack --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsx-transpilier@1.0.0 watch script 'webpack --watch'.
npm ERR! This is most likely a problem with the jsx-transpilier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsx-transpilier
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls jsx-transpilier
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/a119/code/product/npm-debug.log

Process finished with exit code 1

**Comment by rmargam** [comment]
Seems like es6 code will not work for me, I'm not sure why !

**Comment by GProst** [comment]
Yes, sorry, we don't support node.js v4. I've just added this info to README.md
