### ISSUE TITLE
webpack 5 chunks array depreciation

### ISSUE THREAD

**Issue by aniketfuryrocks** [GProst/webpack-clean-obsolete-chunks#34]
Webpack 5 deprecated chunks array in favour of object.
```js
*/51 > /*
let chunks = compilation.chunks.map(chunk => {
     const copy = Object.assign({}, chunk)
     copy.uniqueId = `${compilationName}--${copy.id}`
     return copy
})
```
`.map` needs to be replaced with something related to `Object.keys`

**Errror:**

```
(node:36954) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'map' is deprecated)
    at Set.set.<computed> [as map] (/media/dedsec/Projects/FireJSX/node_modules/webpack/lib/util/deprecation.js:85:4)
    at /media/dedsec/Projects/FireJSX/node_modules/webpack-clean-obsolete-chunks/index.js:51:37
    at Array.reduce (<anonymous>)
    at CleanObsoleteChunks._retrieveAllChunks (/media/dedsec/Projects/FireJSX/node_modules/webpack-clean-obsolete-chunks/index.js:49:23)
    at CleanObsoleteChunks._getObsoleteFiles (/media/dedsec/Projects/FireJSX/node_modules/webpack-clean-obsolete-chunks/index.js:41:23)
    at CleanObsoleteChunks._removeObsoleteFiles (/media/dedsec/Projects/FireJSX/node_modules/webpack-clean-obsolete-chunks/index.js:28:28)
    at Hook.eval [as callAsync] (eval at create (/media/dedsec/Projects/FireJSX/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/media/dedsec/Projects/FireJSX/node_modules/tapable/lib/Hook.js:18:14)
    at /media/dedsec/Projects/FireJSX/node_modules/webpack/lib/Compiler.js:730:27
    at /media/dedsec/Projects/FireJSX/node_modules/neo-async/async.js:2818:7
```

**Platform :** Linux
**Webpack :** 5.1.3
**webpack-clean-obsolete-chunks** : 0.4.0

**Comment by Philipp91** [comment]
I'm getting the same warning. It seems like you know enough to send a PR?

**Comment by aniketfuryrocks** [comment]
I am busy with other work, I'll work on it, as soon as possible.

**Comment by JohnnyFun** [comment]
Seems like webpack's native `output.clean` actually handles what this plugin does. Wonder if this plugin can be deprecated? https://webpack.js.org/configuration/output/#outputclean

**Comment by GProst** [comment]
@JohnnyFun I don't see the option you mentioned in the docs...
I see the mention of the `clean-webpack-plugin` only [here](https://webpack.js.org/guides/output-management/#cleaning-up-the-dist-folder)

**Comment by JohnnyFun** [comment]
hmm, that link takes me to something that looks like this:
![image](https://user-images.githubusercontent.com/8106379/110978312-7597b200-8320-11eb-9fc6-7dd70c8d9ebe.png)

**Comment by GProst** [comment]
@JohnnyFun yeah, now I see it, lol

**Comment by GProst** [comment]
Yes, it seems like Webpack `5.20.0` deprecates this plugin. I'm gonna add a note about it when I have time 👍
Thanks for pointing that out @JohnnyFun
